name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull the Docker image
      run: sudo docker pull atleebugs/exam-registration-uoj:latest
    - name: Delete old container
      run: sudo docker rm -f exam-registration-uoj-container || true
    - name: Run latest docker image
      run: sudo docker run -d -p 443:8080 --name exam-registration-uoj-container atleebugs/exam-registration-uoj
    - name: Prune older docker images
      run: docker image prune -f
